config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/VForWaTer/documentation:
      branch: master
      repo: https://github.com/VForWaTer/documentation
    github.com/VForWaTer/vforwater-portal:
      branch: master
      repo: https://github.com/VForWaTer/vforwater-portal
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/VForWaTer/vforwater-portal git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-sangria-buffalo.sh
        container: qc.acc_beady-green-antelope
  QC.Doc:
    repos:
      github.com/VForWaTer/documentation find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-bronze-gharial.sh
        container: qc.doc_pasty-lilac-guppy
      github.com/VForWaTer/documentation git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-asparagus-badger.sh
        container: qc.doc_scaly-viridian-audemer
      github.com/VForWaTer/documentation markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-pear-audemer.sh
        container: qc.doc_ready-cornflower-spoonbill
      github.com/VForWaTer/documentation restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-amber-whale.sh
        container: qc.doc_frumpy-russet-seal
  QC.Lic:
    repos:
      github.com/VForWaTer/vforwater-portal licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-auburn-sponge.sh
        container: qc.lic_wheezy-amber-seal
  QC.Sec:
    repos:
      github.com/VForWaTer/vforwater-portal bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cyan-blue.sh
        container: qc.sec_pasty-chartreuse-binturong
  QC.Sty:
    repos:
      github.com/VForWaTer/vforwater-portal flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-buff-shrimp.sh
        container: qc.sty_hazy-bronze-husky
      github.com/VForWaTer/vforwater-portal jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-indigo-sheep.sh
        container: qc.sty_breezy-cream-hyrax
  QC.Ver:
    repos:
      github.com/VForWaTer/vforwater-portal get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-pear-wolfhound.sh
        container: qc.ver_gamy-zucchini-ragdoll
timeout: 5400
